
services:
  - type: web
    name: telegram-openrouter-bot
    env: python
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OPENROUTER_KEY
        sync: false
